// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819125149_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Chicago",
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Manufacturing",
                            Name = "Acme Corp",
                            State = "IL"
                        },
                        new
                        {
                            Id = 2,
                            City = "Austin",
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            Name = "Globex Inc",
                            State = "TX"
                        },
                        new
                        {
                            Id = 3,
                            City = "Houston",
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Software",
                            Name = "Initech",
                            State = "TX"
                        },
                        new
                        {
                            Id = 4,
                            City = "Raleigh",
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Pharmaceuticals",
                            Name = "Umbrella LLC",
                            State = "NC"
                        },
                        new
                        {
                            Id = 5,
                            City = "Denver",
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Food & Beverage",
                            Name = "Soylent Corp",
                            State = "CO"
                        },
                        new
                        {
                            Id = 6,
                            City = "San Jose",
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Technology",
                            Name = "Hooli",
                            State = "CA"
                        },
                        new
                        {
                            Id = 7,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Defense",
                            Name = "Stark Industries",
                            State = "NY"
                        },
                        new
                        {
                            Id = 8,
                            City = "Gotham",
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Conglomerate",
                            Name = "Wayne Enterprises",
                            State = "NJ"
                        },
                        new
                        {
                            Id = 9,
                            City = "Portland",
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Food & Beverage",
                            Name = "Wonka Industries",
                            State = "OR"
                        },
                        new
                        {
                            Id = 10,
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Robotics",
                            Name = "Cyberdyne Systems",
                            State = "CA"
                        },
                        new
                        {
                            Id = 11,
                            City = "Boston",
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Biotech",
                            Name = "Massive Dynamic",
                            State = "MA"
                        },
                        new
                        {
                            Id = 12,
                            City = "Seattle",
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Research",
                            Name = "Aperture Science",
                            State = "WA"
                        },
                        new
                        {
                            Id = 13,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Chemicals",
                            Name = "Oscorp",
                            State = "NY"
                        },
                        new
                        {
                            Id = 14,
                            City = "Los Angeles",
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Biotechnology",
                            Name = "Tyrell Corp",
                            State = "CA"
                        },
                        new
                        {
                            Id = 15,
                            City = "Phoenix",
                            CreatedAt = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Aerospace",
                            Name = "Weyland-Yutani",
                            State = "AZ"
                        },
                        new
                        {
                            Id = 16,
                            City = "Charlotte",
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Finance",
                            Name = "Gringotts Ltd",
                            State = "NC"
                        },
                        new
                        {
                            Id = 17,
                            City = "Miami",
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Media",
                            Name = "Prestige Worldwide",
                            State = "FL"
                        },
                        new
                        {
                            Id = 18,
                            City = "New York",
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Import/Export",
                            Name = "Vandelay Industries",
                            State = "NY"
                        },
                        new
                        {
                            Id = 19,
                            City = "Springfield",
                            CreatedAt = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Food & Beverage",
                            Name = "Duff Brewing",
                            State = "OH"
                        },
                        new
                        {
                            Id = 20,
                            City = "Atlanta",
                            CreatedAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Consulting",
                            Name = "Monarch Solutions",
                            State = "GA"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderQty")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Stock")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Laptop",
                            Price = 999.99m,
                            Stock = 50L
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            Stock = 200L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            Stock = 150L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            Stock = 75L
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Monitor 27\"",
                            Price = 349.99m,
                            Stock = 30L
                        });
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
